"use client";
import { useEffect, useMemo, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Slider } from '@/components/ui/slider';
import { Progress } from '@/components/ui/progress';
import { Checkbox } from '@/components/ui/checkbox';
import { AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog';
import { Clock3,ShieldCheck,Check,Download,Upload,RotateCcw,Printer,FileText,LoaderCircle,ChevronRight } from 'lucide-react';
import { scenarios,traits,contextQuestions,TEST_VERSION,blankAnswer,calculateProfile,validatePayload,isComplete,shuffled,localInterpretation,buildReportInput,buttonAmounts,formatEuro,hasButtonAmount,describeButtonDecision } from '@/lib/test';
import type { Answer,Payload,TraitKey } from '@/lib/test';
const hasResponse=(a?:Answer)=>!!a&&(a.action!==null||a.motive!==null||Object.keys(a.ratings).length>0||typeof a.buttonAmount==='number');
function download(name:string,data:string,type='application/json') {
 const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function Choices({label,section,options,value,onChange}:{label:string;section:string;options:{id:string;text:string}[];value:string|null;onChange:(v:string)=>void}) {
 return <fieldset className="answer-block"><legend><span className="question-section">{section}</span>{label}</legend><p className="field-hint">Bitte wähle die Antwort, die am ehesten zutrifft.</p><RadioGroup aria-label={label} value={value??''} onValueChange={onChange}>{[...options,{id:'other',text:'Keine Option passt ausreichend.'}].map(o=><label className={value===o.id?'choice selected':'choice'} key={o.id}><RadioGroupItem value={o.id}/><span>{o.text}</span></label>)}</RadioGroup></fieldset>;
}
function ButtonDecision({answer,onChange}:{answer:Answer;onChange:(change:Partial<Answer>)=>void}) {
 const notPressing=answer.action==='press-0'||answer.action==='other';
 const options=[...scenarios.find(s=>s.id===12)!.actions,{id:'other',text:'Keine Option passt ausreichend.'}];
 return <fieldset className="answer-block button-decision"><legend><span className="question-section">01 · KNOPFENTSCHEIDUNG</span>Betrag und beabsichtigte Anzahl</legend><div className="amount-field"><label htmlFor="button-amount">Ab welchem Betrag pro Druck wärst du bereit, zu drücken?</label><select id="button-amount" value={notPressing?'':answer.buttonAmount??''} disabled={notPressing} onChange={e=>onChange({buttonAmount:e.target.value?Number(e.target.value):null})}><option value="">Mindestbetrag auswählen</option>{buttonAmounts.map(amount=><option value={amount} key={amount}>{formatEuro(amount)} pro Druck</option>)}</select><p className="field-hint">10 Euro bis 10 Millionen Euro pro Druck. Wenn du bei keinem Betrag drücken würdest, wähle unten „Gar nicht“.</p></div><p className="count-question" id="button-count-label">Wie oft würdest du bei diesem Betrag insgesamt drücken wollen?</p><p className="field-hint">Wähle eine ungefähre Anzahl. Sie beschreibt deine Absicht, solange du noch drücken kannst.</p><RadioGroup aria-labelledby="button-count-label" className="button-count-grid" value={answer.action??''} onValueChange={v=>onChange({action:v,...(v==='press-0'||v==='other'?{buttonAmount:null}:{})})}>{options.map(o=><label className={`choice ${answer.action===o.id?'selected':''}`} key={o.id}><RadioGroupItem value={o.id}/><span>{o.text}</span></label>)}</RadioGroup></fieldset>;
}
function ResetControl({onReset}:{onReset:()=>void}) { return <AlertDialog><AlertDialogTrigger asChild><Button variant="ghost"><RotateCcw size={15}/>Neu beginnen</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Neuen Durchlauf beginnen?</AlertDialogTitle><AlertDialogDescription>Die Antworten dieses Durchlaufs werden im Browser zurückgesetzt. Bereits heruntergeladene Dateien bleiben erhalten.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Zurück</AlertDialogCancel><AlertDialogAction onClick={onReset}>Neu beginnen</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>; }
export default function Home() {
 const [stage,setStage]=useState(0),[index,setIndex]=useState(0),[seed,setSeed]=useState(1),[adult,setAdult]=useState(false);
 const [answers,setAnswers]=useState<Record<string,Answer>>({}),[context,setContext]=useState<Record<string,string>>({}),[notice,setNotice]=useState('');
 const [api,setApi]=useState<{configured:boolean;providerLabel?:string}>({configured:false}),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[report,setReport]=useState(''),[reportError,setReportError]=useState('');
 const sliderDraft=useRef<Record<string,number>>({});
 const headingRef=useRef<HTMLHeadingElement>(null),fileRef=useRef<HTMLInputElement>(null),abortRef=useRef<AbortController|null>(null);
 const scenario=scenarios[index],answer=answers[scenario.id]??blankAnswer();
 const payload:Payload={version:TEST_VERSION,adult,context,answers};
 const profile=useMemo(()=>calculateProfile(answers),[answers]);
 const completed=scenarios.filter(s=>isComplete(s,answers[s.id])).length;
 const skipped=scenarios.filter(s=>answers[s.id]?.skipped).length;
 const partial=scenarios.filter(s=>!answers[s.id]?.skipped&&hasResponse(answers[s.id])&&!isComplete(s,answers[s.id])).length;
 const canContinue=!!answer&&!answer.skipped&&answer.action!==null&&answer.motive!==null&&scenario.axes.every(x=>Object.hasOwn(answer.ratings,x.trait))&&(scenario.id!==12||hasButtonAmount(answer));
 const step=stage===0?0:stage===1?1:stage===2||stage===3?2:3;
 const statusRef=useRef({stage,index,completed,partial,skipped});statusRef.current={stage,index,completed,partial,skipped};
 useEffect(()=>{const mc=(document as Document & {modelContext?:{registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!mc?.registerTool)return;const lifecycle=new AbortController();try{void Promise.resolve(mc.registerTool({name:'get_test_progress',description:'Liest nur Testschritt und Anzahl bearbeiteter Situationen. Gibt keine persönlichen Antworten, Profilwerte oder Berichte zurück.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(input!==undefined&&(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length))throw new Error('Keine Argumente erwartet.');return {...statusRef.current,testVersion:TEST_VERSION};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 useEffect(()=>{headingRef.current?.focus();window.scrollTo({top:0,behavior:'instant'});},[stage,index]);
 useEffect(()=>{if(stage!==4)return;let active=true;fetch('/api/report').then(r=>r.json()).then(v=>{if(active&&v&&typeof v==='object'&&'configured' in v&&typeof v.configured==='boolean')setApi({configured:v.configured,providerLabel:'providerLabel' in v&&typeof v.providerLabel==='string'?v.providerLabel:undefined});}).catch(()=>{if(active)setApi({configured:false});});return()=>{active=false;};},[stage]);
 useEffect(()=>()=>abortRef.current?.abort(),[]);
 function go(next:number){setNotice('');setStage(next);}
 function update(change:Partial<Answer>){setAnswers(prev=>({...prev,[scenario.id]:{...(prev[scenario.id]??blankAnswer()),...change,skipped:false}}));setReport('');setConsent(false);setReportError('');}
 function rate(key:TraitKey,value:number|null){const draftKey=`${scenario.id}:${key}`;if(value===null)delete sliderDraft.current[draftKey];else sliderDraft.current[draftKey]=value;update({ratings:{...answer.ratings,[key]:value}});}
 function advance(skip=false){if(skip)setAnswers(prev=>({...prev,[scenario.id]:{...(prev[scenario.id]??blankAnswer()),skipped:true}}));setNotice('');if(index===14)setStage(3);else setIndex(index+1);}
 function openScenario(i:number){setIndex(i);go(2);}
 function start(){setSeed(crypto.getRandomValues(new Uint32Array(1))[0]);go(1);}
 function reset(){abortRef.current?.abort();setStage(0);setIndex(0);setAdult(false);setAnswers({});setContext({});setNotice('');setReport('');setConsent(false);setReportError('');setBusy(false);}
 function saveSession(){download('kontext-durchlauf.json',JSON.stringify({...payload,ui:{stage,index,seed}},null,2));setNotice('Der Dateidownload wurde angefordert. Die Datei enthält persönliche Antworten; bewahre sie entsprechend auf.');}
 async function loadSession(file?:File){if(!file)return;try{if(file.size>512000)throw new Error('Die Datei ist zu groß.');const raw=JSON.parse(await file.text());const clean=validatePayload(raw);abortRef.current?.abort();setBusy(false);setAnswers(clean.answers);setContext(clean.context);setAdult(clean.adult);setSeed(Number.isInteger(raw.ui?.seed)?raw.ui.seed>>>0:1);setIndex(Number.isInteger(raw.ui?.index)&&raw.ui.index>=0&&raw.ui.index<15?raw.ui.index:0);setStage(clean.adult&&Number.isInteger(raw.ui?.stage)&&raw.ui.stage>=0&&raw.ui.stage<=4?raw.ui.stage:0);setReport('');setConsent(false);setReportError('');setNotice('Der gespeicherte Durchlauf wurde geladen.');}catch(e){setNotice(e instanceof Error?e.message:'Die Datei konnte nicht geladen werden.');}finally{if(fileRef.current)fileRef.current.value='';}}
 async function requestReport(){if(!consent||busy||!api.configured)return;setBusy(true);setReportError('');const controller=new AbortController();abortRef.current=controller;const timer=setTimeout(()=>controller.abort(),80000);try{const response=await fetch('/api/report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,consent:true}),signal:controller.signal});const data=await response.json() as {error?:string;report?:string};if(!response.ok)throw new Error(data.error||'Der Bericht konnte nicht erstellt werden.');if(typeof data.report!=='string')throw new Error('Die Antwort des KI-Dienstes war nicht lesbar.');if(!controller.signal.aborted)setReport(data.report);}catch(e){if(!controller.signal.aborted)setReportError(e instanceof Error?e.message:'Der KI-Dienst ist nicht erreichbar.');else setReportError('Die Anfrage wurde beendet. Deine Antworten bleiben erhalten.');}finally{clearTimeout(timer);setBusy(false);}}
 const contextTitle=stage===0?'Persönlichkeit und Reaktionsmuster':stage===1?'Angaben zum Alltag':stage===2?scenario.title:stage===3?'Übersicht der Antworten':'Individuelles Antwortprofil';
 return <div className="app-shell"><header className="site-header"><div className="header-inner"><div className="wordmark"><div><span className="brand-name">Test</span><span className="wordmark-sub">Szenariobasierter Persönlichkeitsfragebogen</span></div></div></div></header>
 <main className="workspace"><aside className="side-panel"><div className="sidebar-heading"><p className="eyebrow">FRAGEBOGEN</p><h2>Ablauf des Durchlaufs</h2></div><nav className="step-list" aria-label="Ablauf">{[{title:'Vorbereitung',note:'Hinweise zur Durchführung'},{title:'Alltagsbezug',note:'Freiwillige Kontextangaben'},{title:'Situationen',note:'15 fiktive Szenarien'},{title:'Antwortprofil',note:'Einordnung und Antwortbelege'}].map((x,i)=><div className={`step ${i===step?'active':i<step?'done':''}`} key={x.title} aria-current={i===step?'step':undefined}><span className="step-number">{i<step?<Check size={14}/>:String(i+1).padStart(2,'0')}</span><div><span className="step-title">{x.title}</span><span className="step-description">{x.note}</span></div></div>)}</nav>
 {(stage===2||stage===3)&&<div className="scenario-navigation"><p className="eyebrow">SITUATIONEN</p><div className="scenario-dots">{scenarios.map((s,i)=><button key={s.id} onClick={()=>openScenario(i)} className={`${stage===2&&i===index?'current ':''}${answers[s.id]?.skipped?'skipped':isComplete(s,answers[s.id])?'answered':hasResponse(answers[s.id])?'partial':''}`} aria-label={`Situation ${s.id}: ${s.title}`} aria-current={stage===2&&i===index?'step':undefined}>{s.id}</button>)}</div><p className="status-line">{completed} vollständig · {partial} teilweise · {skipped} übersprungen</p></div>}
 <div className="side-note"><ShieldCheck size={18}/><div><strong>Umgang mit deinen Angaben</strong><p>Deine Antworten bleiben zunächst im Browser. Ein KI-Bericht benötigt deine gesonderte Freigabe.</p></div></div><div className="session-tools no-print"><p className="eyebrow">DURCHLAUF VERWALTEN</p><Button variant="ghost" onClick={saveSession}><Download size={15}/>Durchlauf speichern</Button><Button variant="ghost" onClick={()=>fileRef.current?.click()}><Upload size={15}/>Durchlauf laden</Button><ResetControl onReset={reset}/></div></aside>
 <section className={`main-panel stage-${stage} ${stage===4?'results-panel':''}`} aria-label="Testbereich">
 {notice&&<p className="notice" role="status">{notice}</p>}
 <div className="section-meta"><span>{stage===0?'01 / EINFÜHRUNG':stage===1?'02 / ALLTAGSBEZUG':stage===2?`SITUATION ${String(index+1).padStart(2,'0')} / 15`:stage===3?'03 / ÜBERBLICK':'04 / AUSWERTUNG'}</span><span>{stage===0?<><Clock3 size={15}/>25–40 Minuten</>:stage===1?'Freiwillig · etwa 2 Minuten':stage===2?`${scenario.length==='kurz'?'Kurze':scenario.length==='mittel'?'Mittlere':'Längere'} Situation`:stage===3?`${completed} vollständig beantwortet`:'Exploratives Antwortprofil'}</span></div>
 {stage===2&&<Progress value={((completed+skipped)/15)*100} aria-label="Bearbeitete Situationen"/>}
 <h1 ref={headingRef} tabIndex={-1} className={stage===2?'scenario-title':''}>{contextTitle}</h1>
 {stage===0&&<><p className="lead">Dieser Fragebogen erfasst deine Entscheidungen, Motive und emotionalen Reaktionen in unterschiedlichen fiktiven Situationen.</p><div className="overview-grid"><div><strong>15 <span>Situationen</span></strong><p>Unterschiedliche Länge und Komplexität</p></div><div><strong>1–10 <span>Antwortskala</span></strong><p>Drei Einschätzungen je Situation</p></div><div><strong>9 <span>Merkmalsbereiche</span></strong><p>Mit transparenten Antwortbelegen</p></div></div><section className="instructions" aria-labelledby="instructions-title"><div className="document-heading"><FileText size={18}/><h2 id="instructions-title">Hinweise zur Durchführung</h2></div><ol><li><strong>Lies die Ausgangssituation.</strong><span>Nimm die beschriebenen Bedingungen als gegeben an. Es ist keine zusätzliche Erklärung erforderlich.</span></li><li><strong>Beurteile deine wahrscheinliche Reaktion.</strong><span>Berücksichtige auch deine übliche Selbstkontrolle. Wähle jeweils eine Handlung und ein Motiv und beantworte die drei Skalen.</span></li><li><strong>Bearbeite den Fragebogen in deinem Tempo.</strong><span>Es gibt keine perfekte Antwort. Einzelne Fragen oder ganze Situationen können ausgelassen und später ergänzt werden.</span></li></ol></section><div className="scope-note"><strong>Einordnung des Verfahrens</strong><p>Explorativer Selbsttest für Erwachsene, wissenschaftlich nicht validiert. Das Ergebnis beschreibt deine Antworten und ersetzt keine klinische Diagnose. Einzelne Situationen behandeln Tod, Erniedrigung oder Machtmissbrauch. Die Zeitangabe ist eine Schätzung.</p></div><div className="start-section"><label className="check-line"><Checkbox checked={adult} onCheckedChange={v=>setAdult(v===true)}/><span>Ich bin mindestens 18 Jahre alt.</span></label><Button className="primary-button" disabled={!adult} onClick={start}>Fragebogen beginnen<ChevronRight size={17}/></Button></div><span className="button-note">Keine automatische Speicherung. Ein ungesicherter Durchlauf geht beim Neuladen verloren.</span><div className="mobile-session-tools no-print"><Button variant="outline" onClick={()=>fileRef.current?.click()}><Upload size={15}/>Gespeicherten Durchlauf laden</Button></div></>}

 {stage===1&&<><p className="lead">Diese Angaben helfen, hypothetische Antworten einzuordnen. Du kannst alles offenlassen. Es werden keine Namen oder Diagnosen abgefragt.</p><div className="context-form">{contextQuestions.map((q,i)=><fieldset className="answer-block" key={q.id}><legend><span className="question-section">ANGABE {String(i+1).padStart(2,'0')} · FREIWILLIG</span>{q.question}</legend><RadioGroup aria-label={q.question} value={context[q.id]??''} onValueChange={v=>{setContext(prev=>({...prev,[q.id]:v}));setReport('');setConsent(false);}}>{q.options.map(x=><label className={context[q.id]===x?'choice selected':'choice'} key={x}><RadioGroupItem value={x}/><span>{x}</span></label>)}</RadioGroup>{context[q.id]&&<button className="text-button" onClick={()=>setContext(prev=>{const copy={...prev};delete copy[q.id];return copy;})}>Angabe entfernen</button>}</fieldset>)}</div><div className="flow-actions"><Button variant="outline" onClick={()=>go(0)}>Zurück</Button><Button className="primary-button" onClick={()=>go(2)}>Zu den Situationen</Button></div></>}
 {stage===2&&<><div className="scenario-copy"><p className="question-section">AUSGANGSSITUATION</p>{scenario.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</div>{answer.skipped&&<p className="notice">Diese Situation ist bisher übersprungen. Eine neue Antwort nimmt sie wieder in die Auswertung auf.</p>}<>{scenario.id===12?<ButtonDecision answer={answer} onChange={update}/>:<Choices section="01 · HANDLUNG" label="Was würdest du am ehesten tun?" options={shuffled(scenario.actions,seed+scenario.id*31)} value={answer.action} onChange={v=>update({action:v})}/>}</><Choices section="02 · MOTIV" label="Welches Motiv würde deine Entscheidung am stärksten bestimmen?" options={shuffled(scenario.motives,seed+scenario.id*67)} value={answer.motive} onChange={v=>update({motive:v})}/>
 <section className="ratings-section" aria-labelledby="ratings-title"><div className="ratings-heading"><p className="question-section">03 · PERSÖNLICHE EINSCHÄTZUNG</p><h2 id="ratings-title">Wie würdest du dich dabei fühlen?</h2><p className="field-hint">Wähle für jede Skala einen Wert von 1 bis 10.</p></div>{scenario.axes.map(axis=>{const value=answer.ratings[axis.trait],answered=typeof value==='number',omitted=value===null;return <fieldset className="axis" key={`${scenario.id}-${axis.trait}`}><legend id={`axis-${axis.trait}`}>{axis.question}</legend><div className="axis-meta"><span className="axis-reading">{answered?`${value} / 10`:omitted?'Ausgelassen':'Noch unbeantwortet'}</span><button className="text-button" onClick={()=>rate(axis.trait,null)}>Skala auslassen</button></div><Slider min={1} max={10} step={1} className={!answered?'unanswered-slider':''} value={answered?[value]:[5]} onValueChange={v=>{if(v.length)rate(axis.trait,v[0]);}} onPointerUp={()=>rate(axis.trait,sliderDraft.current[`${scenario.id}:${axis.trait}`]??value??5)} ref={el=>{const thumb=el?.querySelector('[role="slider"]');thumb?.setAttribute('aria-labelledby',`axis-${axis.trait}`);thumb?.setAttribute('aria-valuetext',answered?`${value} von 10`:'Noch unbeantwortet; Wert auswählen');}} aria-labelledby={`axis-${axis.trait}`}/><div className="axis-anchors"><span>1 · {axis.low}</span><span>10 · {axis.high}</span></div><div className="number-buttons" role="group" aria-label={axis.question}>{Array.from({length:10},(_,i)=><button key={i} className={value===i+1?'picked':''} aria-pressed={value===i+1} onClick={()=>rate(axis.trait,i+1)} aria-label={`${axis.question} ${i+1} von 10`}>{i+1}</button>)}</div></fieldset>;})}</section>
 <div className="flow-actions"><Button variant="outline" onClick={()=>index>0?setIndex(index-1):go(1)}>Zurück</Button><div><Button variant="ghost" onClick={()=>advance(true)}>Situation überspringen</Button><Button className="primary-button" disabled={!canContinue} onClick={()=>advance()}>{index===14?'Durchlauf prüfen':'Weiter'}</Button></div></div>{!canContinue&&!answer.skipped&&<p className="button-note">{scenario.id===12?'Wähle eine Anzahl und ein Motiv; bei mindestens einem Druck auch den Mindestbetrag. Beantworte die drei Skalen oder lasse sie ausdrücklich aus.':'Wähle Handlung und Motiv. Beantworte die drei Skalen oder lasse sie ausdrücklich aus.'}</p>}<div className="mobile-session-tools no-print"><Button variant="outline" onClick={saveSession}><Download size={15}/>Durchlauf speichern</Button><Button variant="ghost" onClick={()=>go(3)}>Überblick</Button></div></>}
 {stage===3&&<><p className="lead">Du kannst Antworten ergänzen oder direkt auswerten. Ausgelassene Skalen werden nicht als mittlere oder niedrige Werte behandelt.</p><div className="review-list">{scenarios.map((s,i)=>{const a=answers[s.id];const status=a?.skipped?'Übersprungen':isComplete(s,a)?'Vollständig':hasResponse(a)?'Teilweise':'Offen';return <button className="review-row" key={s.id} onClick={()=>openScenario(i)}><span className="review-number">{String(s.id).padStart(2,'0')}</span><span>{s.title}</span><span className={`review-status ${status==='Vollständig'?'complete':''}`}>{status}</span></button>;})}</div><div className="info-box"><h3>Was wird ausgewertet?</h3><p>Die Intensität deiner Skalenantworten, ihre Spannweite und deine gewählten Handlungen und Motive. Erst ab drei Skalenantworten wird ein Bereichswert angezeigt.</p></div><div className="flow-actions"><Button variant="outline" onClick={()=>openScenario(14)}>Zurück</Button><Button className="primary-button" onClick={()=>go(4)}>Antwortprofil anzeigen</Button></div></>}
 {stage===4&&<><p className="lead">{completed} Situationen vollständig beantwortet · {partial} teilweise · {skipped} übersprungen. Die Werte beziehen sich auf diesen Durchlauf.</p><div className="result-callout"><strong>Antwortstärke ist keine Diagnose.</strong><p>Die Skala zeigt deine Selbsteinschätzungen. Ohne wissenschaftliche Validierung gibt es hier keine klinischen Grenzwerte, Erkrankungswahrscheinlichkeiten oder Vergleiche mit anderen Menschen.</p></div><div className="document-heading profile-heading"><FileText size={18}/><h2>Merkmalsbereiche im Überblick</h2></div><div className="profile-list">{profile.map(t=><div className="score-row" key={t.key}><div className="score-heading"><h3>{t.name}</h3><span>{t.score===null?'Zu wenig Information':`${String(t.score).replace('.',',')} / 10`}</span></div><p>{t.description}</p><div className="score-track" aria-label={t.score===null?`${t.name}: zu wenig Information`:`${t.name}: ${t.score} von 10`}><span style={{width:t.score===null?'0%':`${t.score/10*100}%`}}/></div><div className="score-meta"><span>{t.count} / 5 Skalen beantwortet</span><span>{t.count>0?`Spannweite ${t.min}–${t.max}`:'Keine Skalenwerte'}</span></div><details><summary>Antwortbelege ansehen</summary><div className="trait-evidence">{t.observations.length?t.observations.map(o=><p key={o.scenarioId}><strong>Situation {o.scenarioId} · {o.value}/10</strong><br/>{o.question}</p>):<p>Keine auswertbaren Skalenantworten.</p>}</div></details></div>)}</div>
 <section className="local-report"><div className="report-label"><FileText size={17}/><span>ERLÄUTERUNG DES ANTWORTPROFILS · REGELBASIERT</span></div>{localInterpretation(payload).map(s=><div className="report-section" key={s.title}><h2>{s.title}</h2><p>{s.text}</p></div>)}</section>
 <section className="ai-section" aria-labelledby="ai-title"><div className="report-label"><span>AUSFÜHRLICHER PERSÖNLICHER BERICHT</span></div><h2 id="ai-title">Persönlicher KI-Bericht</h2>{!api.configured?<><p>Die KI-Anbindung ist vorbereitet. Sobald der Betreiber einen KI-Dienst angeschlossen hat, kannst du hier einen persönlichen Bericht mit 1.200–1.800 Wörtern erstellen lassen.</p><p className="status-line">Aktuell wird kein Antwortprofil an einen KI-Dienst übertragen. Die Einordnung oben entsteht aus festen Regeln.</p></>:<><p>Der Bericht verbindet dein Antwortprofil mit konkreten Situationen. Übermittelt werden die gewählten Antworten, freiwilligen Kontextangaben und das berechnete Profil an {api.providerLabel||'den konfigurierten KI-Dienst'}. Namen werden nicht abgefragt. Google kann die Angaben gemäß den Bedingungen der API-Stufe verarbeiten.</p><p className="status-line">Google gibt an, dass Inhalte der kostenlosen Gemini-API-Stufe zur Verbesserung seiner Produkte verwendet werden können. Für die bezahlte Stufe nennt Google eine abweichende Regel: Inhalte werden dafür nicht verwendet. Die Stufe dieses Schlüssels kann die App nicht erkennen. Prüfe sie in Google AI Studio und stimme nur zu, wenn du mit der Übermittlung dieser sensiblen Selbstauskünfte einverstanden bist. <a href="https://ai.google.dev/gemini-api/docs/pricing" target="_blank" rel="noreferrer">Details zu Googles API-Datenverarbeitung und Tarifen</a>.</p><label className="check-line no-print"><Checkbox checked={consent} disabled={busy} onCheckedChange={v=>setConsent(v===true)}/><span>Ich möchte diese Angaben für meinen Bericht an diesen KI-Dienst übermitteln.</span></label><Button className="primary-button no-print" disabled={!consent||busy||profile.every(x=>x.score===null)} onClick={requestReport}>{busy?<><LoaderCircle className="spin" size={16}/>Bericht wird erstellt</>:report?'Bericht erneut erstellen':'KI-Bericht erstellen'}</Button>{reportError&&<p className="notice error-notice" role="alert">{reportError}</p>}</>}{report&&<article className="generated-report">{report.split(/\n{2,}/).map((p,i)=><p key={i}>{p}</p>)}</article>}</section>
 <details className="all-evidence"><summary>Alle gewählten Handlungen und Motive</summary><div>{scenarios.map(s=>{const a=answers[s.id];return <div className="evidence-row" key={s.id}><h3>{s.id}. {s.title}</h3>{a?.skipped?<p>Übersprungen.</p>:<><p><strong>Handlung:</strong> {a?.action==='other'?'Keine Option passt':s.actions.find(x=>x.id===a?.action)?.text??'Nicht beantwortet'}</p>{s.id===12&&<p><strong>Knopfentscheidung:</strong> {describeButtonDecision(a)}</p>}<p><strong>Motiv:</strong> {a?.motive==='other'?'Keine Option passt':s.motives.find(x=>x.id===a?.motive)?.text??'Nicht beantwortet'}</p></>}</div>;})}</div></details><div className="flow-actions no-print"><Button variant="outline" disabled={busy} onClick={()=>go(3)}>Antworten bearbeiten</Button><div><Button variant="outline" onClick={()=>download('kontext-antwortprofil.json',JSON.stringify(buildReportInput(payload),null,2))}><Download size={15}/>Profil herunterladen</Button><Button onClick={()=>window.print()}><Printer size={15}/>Drucken / PDF</Button></div></div></>}
 {stage!==0&&stage!==2&&<div className="mobile-session-tools no-print"><Button variant="outline" onClick={saveSession}><Download size={15}/>Durchlauf speichern</Button><Button variant="ghost" onClick={()=>fileRef.current?.click()}><Upload size={15}/>Durchlauf laden</Button><ResetControl onReset={reset}/></div>}
 </section></main><footer className="site-footer"><span>Test</span><span>Selbstreflexion mit nachvollziehbaren Antwortbelegen.</span><a href="https://www.nice.org.uk/guidance/cg77/chapter/Recommendations" target="_blank" rel="noreferrer">Grenzen klinischer Einordnung</a></footer><input aria-label="Gespeicherten Durchlauf auswählen" ref={fileRef} type="file" accept=".json,application/json" hidden onChange={e=>loadSession(e.target.files?.[0])}/></div>;
}
